using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TaskManagement.Bot.Infrastructure.Entities;

namespace TaskManagement.Bot.Infrastructure.Configurations
{
    public class ReportConfiguration : IEntityTypeConfiguration<Report>
    {
        public void Configure(EntityTypeBuilder<Report> builder)
        {
            builder.ToTable("Reports");

            builder.HasKey(r => r.Id);

            builder.Property(r => r.Title)
                .IsRequired()
                .HasMaxLength(255);

            builder.Property(r => r.Content)
                .IsRequired();

            builder.Property(r => r.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);

            builder.Property(r => r.TargetUser)
                .HasMaxLength(100);

            builder.Property(r => r.ClanId)
                .HasMaxLength(100);

            builder.Property(r => r.ThreadId)
                .HasMaxLength(100);

            builder.Property(r => r.Type)
                .HasConversion<int>();

            builder.Property(r => r.TimeRange)
                .HasConversion<int?>();

            builder.Property(r => r.StatusFilter)
                .HasConversion<int?>();

            builder.Property(r => r.StartDate);

            builder.Property(r => r.EndDate);

            builder.Property(r => r.TotalTasks)
                .HasDefaultValue(0);

            builder.Property(r => r.CompletedTasks)
                .HasDefaultValue(0);

            builder.Property(r => r.InProgressTasks)
                .HasDefaultValue(0);

            builder.Property(r => r.PendingTasks)
                .HasDefaultValue(0);

            builder.Property(r => r.OverdueTasks)
                .HasDefaultValue(0);

            builder.Property(r => r.IsAutoGenerated)
                .HasDefaultValue(false);

            builder.Property(r => r.CreatedAt)
                .HasDefaultValueSql("GETUTCDATE()");

            builder.Property(r => r.UpdatedAt);

            builder.Property(r => r.IsDeleted)
                .HasDefaultValue(false);

            builder.HasIndex(r => r.CreatedBy);

            builder.HasIndex(r => r.Type);

            builder.HasIndex(r => r.StartDate);

            builder.HasIndex(r => r.EndDate);

            builder.HasIndex(r => r.StatusFilter);

            builder.HasIndex(r => r.TimeRange);

            builder.HasIndex(r => r.ClanId);

            builder.HasIndex(r => r.ThreadId);

            builder.HasIndex(r => new { r.CreatedBy, r.StartDate, r.EndDate });

            builder.HasQueryFilter(r => !r.IsDeleted);
        }
    }
}