using TaskManagement.Bot.Infrastructure.Enums;

namespace TaskManagement.Bot.Infrastructure.Entities;

public class Report : BaseEntity
{
    public required string Title { get; set; }
    public ReportType Type { get; set; }

    public string? TargetUser { get; set; }
    public TimeRange? TimeRange { get; set; }
    public TaskFilterStatus? StatusFilter { get; set; }

    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }

    public string? ClanId { get; set; }
    public string? ThreadId { get; set; }

    public int TotalTasks { get; set; }
    public int CompletedTasks { get; set; }
    public int InProgressTasks { get; set; }
    public int PendingTasks { get; set; }
    public int OverdueTasks { get; set; }

    public required string Content { get; set; }

    public required string CreatedBy { get; set; }
    public bool IsAutoGenerated { get; set; }
}