using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TaskManagement.Bot.Migrations
{
    /// <inheritdoc />
    public partial class RemoveReportTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Reports");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Reports",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ClanId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CompletedTasks = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    Content = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "GETUTCDATE()"),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    EndDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    InProgressTasks = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    IsAutoGenerated = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    OverdueTasks = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    PendingTasks = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    StartDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    StatusFilter = table.Column<int>(type: "int", nullable: true),
                    TargetUser = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ThreadId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    TimeRange = table.Column<int>(type: "int", nullable: true),
                    Title = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: false),
                    TotalTasks = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    Type = table.Column<int>(type: "int", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Reports", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Reports_ClanId",
                table: "Reports",
                column: "ClanId");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_CreatedBy",
                table: "Reports",
                column: "CreatedBy");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_CreatedBy_StartDate_EndDate",
                table: "Reports",
                columns: new[] { "CreatedBy", "StartDate", "EndDate" });

            migrationBuilder.CreateIndex(
                name: "IX_Reports_EndDate",
                table: "Reports",
                column: "EndDate");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_StartDate",
                table: "Reports",
                column: "StartDate");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_StatusFilter",
                table: "Reports",
                column: "StatusFilter");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_ThreadId",
                table: "Reports",
                column: "ThreadId");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_TimeRange",
                table: "Reports",
                column: "TimeRange");

            migrationBuilder.CreateIndex(
                name: "IX_Reports_Type",
                table: "Reports",
                column: "Type");
        }
    }
}
